Build fixes for libshortfin using Windows/MSVC. (#210)
Fixes for various warnings and errors observed when building with MSVC
on my local dev machine:
* Implicit conversion from double to float
*
`D:\dev\projects\SHARK-Platform\libshortfin\src\shortfin/array/dims.h(118):
error C2440: 'reinterpret_cast': cannot convert from '__int64' to
'shortfin::array::InlinedDims<iree_hal_dim_t,std::allocator<iree_host_size_t>>::const_iterator::difference_type'`
* Missing symbols / includes
*
`D:\dev\projects\SHARK-Platform\libshortfin\src\shortfin/local/messaging.h(143):
warning C4910:
'shortfin::local::TypedFuture<shortfin::local::Message::Ref>':
'__declspec(dllexport)' and 'extern' are incompatible on an explicit
instantiation`
* Implicit/explicit type conversions with `string` and `c_str` in
https://en.cppreference.com/w/cpp/filesystem/path

I'm still seeing `STATUS_DLL_NOT_FOUND` style errors when building with
`-DSHORTFIN_BUILD_DYNAMIC=ON`:
```
    Error running test executable.

      Path: 'D:/dev/projects/SHARK-Platform/libshortfin/build/cmake/default/src/shortfin/support/shortfin_support_test.exe'
      Working directory: 'D:/dev/projects/SHARK-Platform/libshortfin/build/cmake/default/src/shortfin/support'
      Result: Exit code 0xc0000135
```