Build sharktank packages nightly. (#404)
Progress on https://github.com/nod-ai/SHARK-Platform/issues/294. Once
this is merged the nightly package builds will start pushing
`sharktank-{VERSION}-py3-none-any.whl` to
https://github.com/nod-ai/SHARK-Platform/releases/tag/dev-wheels
alongside the existing shortfin wheels.

Tested at
https://github.com/ScottTodd/SHARK-Platform/actions/runs/11621153296/job/32364368882
(ignore the push failure at the end, missing a token).

---

Note that the 250KB Python wheel can be _installed_ standalone, but
actually _using_ it will need version bumps across projects and more
work. In particular, I hit

1. Using iree-turbine from pypi:
    ```
    from sharktank import ops
    ...

ImportError: cannot import name 'dynamic_dim' from 'torch.export'
(/home/nod/dev/scratch/shark-platform/3.11.venv/lib/python3.11/site-packages/torch/export/__init__.py)
    ```
That may be fixed by https://github.com/iree-org/iree-turbine/pull/233
2. After installing iree-turbine from source:
    ```
    from sharktank import ops
    ...

        from gguf import GGUFReader, GGUFValueType
    ModuleNotFoundError: No module named 'gguf'
    ```

Full logs here:
https://gist.github.com/ScottTodd/4cd0c343a92375e7fbdaaf37c38bfc06