[shortfin] Fix mobilenet_server example by filling mapped storage. (#241)
I saw this error trying to run this example:
```
RuntimeError: Async exception on <Worker 'device-hostcpu:0:0@0'>): '_shortfin_default.lib.array.storage' object has no attribute 'data'
```

I looked around for and API that would allow for copying from
`array.array` (https://docs.python.org/3/library/array.html) into
shortfin's `array.storage`
(https://shortfin.readthedocs.io/en/latest/reference.html#shortfin_default.lib.array.storage)
and only found `map()`.

Quite possible that I'm missing something, or there is an easier
interface that isn't fully plumbed through to Python and the
documentation yet.

Logs of this running:
https://gist.github.com/ScottTodd/da8c1d6805584490c46e4d2086404a6b